name:                freana
version:             0.1.0.0
github:              "brenoafb/freana"
license:             BSD3
author:              "Breno Fatureto"
maintainer:          "breno.afb@gmail.com"
copyright:           "2021 Breno Fatureto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/brenoafb/freana#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- xeno
- pretty-simple
- uniplate
- containers

library:
  source-dirs: src

executables:
  freana-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - freana

tests:
  freana-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - freana
